"""empty message

Revision ID: 8d542ffba475
Revises: 
Create Date: 2020-06-06 18:31:47.103338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d542ffba475'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ContactMessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ContactMessage_email'), 'ContactMessage', ['email'], unique=False)
    op.create_index(op.f('ix_ContactMessage_subject'), 'ContactMessage', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ContactMessage_subject'), table_name='ContactMessage')
    op.drop_index(op.f('ix_ContactMessage_email'), table_name='ContactMessage')
    op.drop_table('ContactMessage')
    # ### end Alembic commands ###
