"""Create ContactMessage table.

Revision ID: cb67fcb42a94
Revises: 
Create Date: 2020-06-08 15:44:10.326716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb67fcb42a94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ContactMessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ContactMessage_email_id'), 'ContactMessage', ['email_id'], unique=False)
    op.create_index(op.f('ix_ContactMessage_subject'), 'ContactMessage', ['subject'], unique=False)
    op.create_index(op.f('ix_ContactMessage_time_created'), 'ContactMessage', ['time_created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ContactMessage_time_created'), table_name='ContactMessage')
    op.drop_index(op.f('ix_ContactMessage_subject'), table_name='ContactMessage')
    op.drop_index(op.f('ix_ContactMessage_email_id'), table_name='ContactMessage')
    op.drop_table('ContactMessage')
    # ### end Alembic commands ###
